openapi: 3.0.0
info:
  title: Brainwave Health API
  version: 1.0.0
  description: |
    Health endpoints provide live and readiness status for the Brainwave service.
    Use these endpoints for monitoring, load balancers, or uptime checks.

tags:
  - name: Health
    description: |
      Endpoints for checking service health:
      - `/live` for liveness
      - `/ready` for readiness including build info and dependencies

paths:
  /health/live:
    get:
      tags:
        - Health
      summary: Liveness check
      description: Returns the current live status of the service. Typically used by orchestrators to verify the service is running.
      responses:
        '200':
          description: Service liveness status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveStatus'

  /health/ready:
    get:
      tags:
        - Health
      summary: Readiness check
      description: Returns detailed readiness information, including build info, dependencies, and uptime.
      responses:
        '200':
          description: Service readiness status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyStatus'

components:
  schemas:
    LiveStatus:
      type: object
      description: Liveness status of the service
      properties:
        status:
          type: string
          example: 'OK'
          description: 'Current live status, e.g., OK'

    ReadyStatus:
      type: object
      description: Readiness status including build info and dependencies
      properties:
        status:
          type: string
          example: 'OK'
          description: 'Current readiness status, e.g., OK'
        buildInfo:
          type: object
          description: 'Build metadata for the running service'
          properties:
            version:
              type: string
              example: '1.0.0'
              description: 'Application version'
            buildTime:
              type: string
              format: date-time
              example: '2026-02-25T14:00:00.000Z'
              description: 'Build timestamp in UTC ISO 8601'
            gitSha:
              type: string
              example: 'a1b2c3d4e5f6'
              description: 'Git commit SHA of the build'
        dependencies:
          type: object
          description: 'Status of external dependencies required by the service'
          properties:
            database:
              type: boolean
              example: true
              description: 'Whether the database connection is healthy'
        uptime:
          type: number
          format: float
          example: 12345.67
          description: 'Service uptime in seconds'
